### ISSUE TITLE
The component showAt rendering a < div > tag

### ISSUE THREAD

**Issue by fabriciohendrix** [apertureless/vue-breakpoints#4]
How do I do to do not render a <  div > tag outside my content inside <show-at>?

**Comment by apertureless** [comment]
You can't.
Vue.js always needs a single root element to render. Support for multiple root elements is on the roadmap for version 3 if I remember correctly.

As `vue-breakpoints` is utilizing slots, you can pass multiple elements into the slot. In order to work properly they need to be wrapped into a div.

**Comment by fabriciohendrix** [comment]
Thanks for the help, Jakub!!

**Comment by apertureless** [comment]
You're welcome!
