### ISSUE TITLE
Can I use more than one show at a time without using a hide at?

### ISSUE THREAD

**Issue by Bowens20832** [apertureless/vue-breakpoints#8]
I keep getting this warning: You must have one child inside a <showAt> or <hideAt/> component. 

In my components, I use two or more different show ats, but no hide at's. Could this be the issue?

Ex: 
```
<show-at breakpoint="small">
      <component />
    </show-at>
    <show-at breakpoint="mediumAndAbove">
      <component2 />
</show-at>
```

**Comment by Bowens20832** [comment]
@apertureless

**Comment by apertureless** [comment]
Hey @Bowens20832 
sorry for the late reply. Somehow I did not got any notification.

Yes, sure you can use multiple `show-at` components or multiple `hide-at` components.

It is however important that you have only 1 root component inside it. Because the `show-at` and `hide-at` components work with slots. And right now you can only have 1 root node in slots in vue.js

**This does works**


```js

<show-at breakpoint="small">
	<div>🐶</div>
</show-at>

<show-at breakpoint="medium">
	<div>🐱</div>
</show-at>
```

**This does not work**

```js
<show-at breakpoint="medium">
	<div>🐱</div>
    <div>🐱</div>
</show-at>

```

> The last on did not work because you have two childs in the slot.
